Add reducers and actions
Alusp/bookstore-with-react pull request #2
Opened 2022-09-21 20:58 UTC by Alusp

## I implemented the following in this PR:

- [ ] Add Redux Toolkit(npm install react-redux @reduxjs/toolkit).
- [ ] Structure my application files using a "feature folder" approach and use the [ducks pattern](https://github.com/erikras/ducks-modular-redux) for your Redux files.
- [ ] configure my Redux Store and write actions and reducer for adding and removing books.
- [ ] Define action types for adding and removing a book.
- [ ] Set the initial state to be an empty array of books.
- [ ] Export Action Creators for your actions.
- [ ] Write your reducer and export it as default.
- [ ] Define state changes for the actions that you created.
- [ ] In case of unknown action - return the current state.

2022-09-21 22:50 UTC, Munsa1 requested changes
Hi @Alusp, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
:heavy_check_mark: Descriptive Readme
:heavy_check_mark: Passing Linters
:heavy_check_mark: Correct Gitflow
## Required Changes ♻️
_Check the comments under the review._
- [ ] Kindly implement the following requirements for `categories.js`
![image](https://user-images.githubusercontent.com/81932478/191623956-e115a07b-d9f5-4651-84dc-dd5fa89150f7.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-21 22:50 UTC, Munsa1 commented on src/redux/configureStore.js
> +import booksReducer from './books/books';
- [x] `configureStore.js` should import `configureStore`  from @reduxjs/toolkit. Kindly fix it.
- [x] `configureStore.js` should import `categories` from `src/redux/categories`. Kindly fix it.

2022-09-23 11:36 UTC, uwadonat approved these changes
## Hi @Alusp,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# highlights
- Descriptive pull request message ✔
![approval](https://user-images.githubusercontent.com/65860678/191952003-a77461c8-d1ed-4f29-9862-23ec9c6d5c22.gif)
️

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-09-23 11:46 UTC, Alusp commented
Thanks very much for the review @uwadonat

2022-09-23 11:47 UTC, merged